Project.name.requires=IS_NOT_EMPTY(error_message=T('The field name can not be empty!'))
Sprint.name.requires=IS_NOT_EMPTY(error_message=T('The field name can not be empty!'))
Sprint.weeks.requires=IS_NOT_EMPTY(error_message=T('Choose how many weeks for your sprint!'))
Story.title.requires=IS_NOT_EMPTY(error_message=T('This field can not be empty!'))
Story.benefit.requires=IS_NOT_EMPTY(error_message=T('This field can not be empty!'))
Story.story_points.requires=IS_NOT_EMPTY(error_message=T('This field can not be empty!'))
